baseURL = 'https://juhotervo.fi'
languageCode = 'fi-fi'
title = 'Blogi - Juho Tervo'
theme = 'hugo-bearblog'

enableRobotsTXT = true

[params]
	description = "Kauhukertomuksia"
	hideMadeWithLine = true
